### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by yourh3ro** [HemulGM/ChatGPT#10]
Где сборки под Linux?
Либо инструкция как собрать под Linux?

**Comment by HemulGM** [comment]
Чуть позже выложу сборки.

**Comment by fisuri** [comment]
Hello, can I make a flatpak version instead of a native one?

**Comment by fisuri** [comment]
Можно ли сделать flatpak версию вместо нативной?

**Comment by HemulGM** [comment]
Думаю да. Изучу вопрос с flatpack. Сейчас у меня нет возможности напрямую собирать под Линукс. Нужно подготавливать окружение для сборки. Сборку под Линукс делали мне люди из сообщества и тестировали на разных дистрибутивах. Успешно, надо сказать. Проблема пока выявилась только на Астра Линукс (нужно ставить доп. пакеты) и на Астра Линукс Самара.

**Comment by StasGrishaevTutu** [comment]
Под macOS так же сборки можно ожидать попозже ?

**Comment by HemulGM** [comment]
> Под macOS так же сборки можно ожидать попозже ?  

Они уже есть. Только не опубликованы. На следующей неделе выложу все сборки. Включая андроид. Возможно сразу с подсветкой синтаксиса в полях кода.

**Comment by yourh3ro** [comment]
Может есть смысл создать Makefile или набор скриптов для сборки под разные платформы?

**Comment by HemulGM** [comment]
> Может есть смысл создать Makefile или набор скриптов для сборки под разные платформы?

Delphi бесплатной версии не позволяет собирать под Linux, а если использовать версию со сборкой под Linux, то нужно либо подключать компьютер с установленным Linux, либо виртуалку. Т.е. сборка в любом случае будет под Windows, с использованием SDK дистрибутива. То же касается и MacOS и iOS. 
Вдобавок, сейчас я вношу изменения в стандартную библиотеку для повышения производительности работы с текстом и подсветки синтаксиса, что происходит на последней версии (11.3). 
По этому, собрать самому будет сложнее пока. К сожалению. 
Теоретически, собрать скрипт для сборки можно и, думаю, нужно. Что позволит не настраивать среду.

**Comment by HemulGM** [comment]
> Под macOS так же сборки можно ожидать попозже ?

Сборка под MacOS https://github.com/HemulGM/ChatGPT/releases

**Comment by HemulGM** [comment]
> Где сборки под Linux? Либо инструкция как собрать под Linux?

https://github.com/HemulGM/ChatGPT/releases/tag/v1.0.10-linux-64

**Comment by HemulGM** [comment]
@yourh3ro проверь, пожалуйста, сборку под Линукс
