### ISSUE TITLE
Select between gpt3.5-turbo and gpt-4

### ISSUE THREAD

**Issue by viktor02** [HemulGM/ChatGPT#12]
Add support for switching between models in the interface. Openai has an api method to get a list of models for a particular token

---------

Добавьте поддержку для переключения между моделями в интерфейсе. 
У openai есть api метод для получения списка моделей для конкретного токена

https://platform.openai.com/docs/api-reference/models/list

**Comment by HemulGM** [comment]
Разве у gpt-4 такой же api? Т.е. не нужно ли для gpt-4 адаптировать текущее апи? 
Если эта модель работает также (формат ответов и запросов одинаковый), то это без проблем можно сделать

**Comment by viktor02** [comment]
Хм, ну как я понял, если используется endpoint `https://api.openai.com/v1/completions` то нужно адаптировать. Если используется `https://api.openai.com/v1/chat/completions`, то адаптировать не надо, они совместимы. GPT-3.5-turbo работает и там, и там. GPT-4 только в v1/chat

Здесь мои результаты https://hastebin.skyra.pw/wevahobiwa.swift

**Comment by HemulGM** [comment]
Ну gpt-3.5 тоже только с chat/completions работает, насколько я помню. 
И т.е. ответ от gpt-4 такой же как и при работе с gpt-3.5? Если так, то проблем нет. 
Просто, вроде бы обещали, что GPT-4 сможет в смешанный контент, а не только текст как GPT-3.5.

**Comment by viktor02** [comment]
> Просто, вроде бы обещали, что GPT-4 сможет в смешанный контент

Ну это я думаю в будущем сделают, сейчас нет ничего такого в документации к api

**Comment by HemulGM** [comment]
> Ну это я думаю в будущем сделают, сейчас нет ничего такого в документации к api

В документации нет, я по ней и делал. Но за неимением Премиум подписки я протестировать не могу.

**Comment by viktor02** [comment]
Могу протестировать, если закоммитите последнюю версию или сделаете билд

> Добавил выбор модели. Протестировать gpt-4 всё ещё не могу. Если будет возможность - отпишитесь. Билд будет на этой неделе. Добавил так же настройки поощрения и наказания по частоте использования одних и тех же токенов и некоторые другие настройки

**Comment by HemulGM** [comment]
Мне предоставили доступ к gpt-4. Всё работает. Выбор модели уже сделал. Можно выбрать из трёх актуальных (gpt-4, gpt-4-32k и gpt-3.5-turbo), а также, можно указать вручную на будущее, если не успею актуализировать список. 
Добавил ещё параметры: максимальное количество токенов модели и количество токенов на запрос, поощрение и наказание за переиспользование токенов и т.д.

Доделаю ещё некоторые вещи и опубликую новую версию

**Comment by HemulGM** [comment]
Обновил
