### ISSUE TITLE
не работает частичный выбор текста с прокруткой колесом

### ISSUE THREAD

**Issue by dreamer2** [HemulGM/ChatGPT#15]
при необходимости отметить и скопировать часть текста не помещающегося на экран отметка и прокрутка не работают

**Comment by HemulGM** [comment]
Что значит отметка не работает?

**Comment by dreamer2** [comment]
отметить можно только то что на экране, прокрутка не работает вместе с отметкой
win10

**Comment by HemulGM** [comment]
Прокрутку колёсиком разрешил. Билд будет на этой неделе. Отпишу сюда.
По поводу стягивания мыши к краю - подумаю.

**Comment by HemulGM** [comment]
Обновил
