### ISSUE TITLE
Не запускается версия 64 бит

### ISSUE THREAD

**Issue by Valirius** [HemulGM/ChatGPT#17]
Windows 11 Pro 21H2 64 bit
Проц AMD 5600x, если это важно по какой-то причине)
ОЗУ 32 Гб

![image](https://user-images.githubusercontent.com/22143019/236388958-a3383196-e7b6-4aaa-8f0f-bdeef9b8f9f0.png)
Файлик ChatGPT - это как раз новая версия - она не запускается вообще никак. Запускаешь и даже в диспетчере заметить как она появляется - не успеваю.

32 версия работает, и прошлая версия тоже работает

Кстати круто было бы версионность какую-то внедрить. Чтобы внутри посмотреть было где то какая версия, а то не удобно отслеживать что изменилось и баги ловить)

Есть способ как-то отладить мне у себя что с ней там происходит?

**Comment by dreamer2** [comment]
для х64 приложений нужна х64 sk4d.dll

**Comment by Valirius** [comment]
Ха, и действительно. Они разные, вижу)
Всё. Можно закрывать. Но версионность круто было бы внедрить

**Comment by dreamer2** [comment]
про версии поддержу - если можно было бы в файлы добавить дату сборки было бы здорово

**Comment by HemulGM** [comment]
Да, уже собираюсь)
