### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by OleksiyPenkov** [HemulGM/ChatGPT#23]
Platform: Windows
Could you, please, implement own Proxy Settings instead (or in addition to) of use of system ones?

**Comment by HemulGM** [comment]
No problem. I already thought about it

**Comment by HemulGM** [comment]
![image](https://user-images.githubusercontent.com/22197242/236609146-a9f4cc47-61db-4937-b638-f2c0c742f96a.png)
Done

**Comment by dreamer2** [comment]
proxy type https?

**Comment by HemulGM** [comment]
yes

**Comment by OleksiyPenkov** [comment]
It works just fine. Thanks a lot!
