### ISSUE TITLE
crash on some text input

### ISSUE THREAD

**Issue by dreamer2** [HemulGM/ChatGPT#24]
after request
help me with decode "&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-"

get app crash
![image](https://user-images.githubusercontent.com/2936985/236781256-0cff2b0b-40d1-4606-a20a-ad14d2f90128.png)

bugged text stored in chats.json and crash happens again on app restart

**Comment by HemulGM** [comment]
> after request
> help me with decode "&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-"
> 
> get app crash
> ![image](https://user-images.githubusercontent.com/2936985/236781256-0cff2b0b-40d1-4606-a20a-ad14d2f90128.png)
> 
> bugged text stored in chats.json and crash happens again on app restart

Thanks a lot, I'll fix it

**Comment by HemulGM** [comment]
> after request
> help me with decode "&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-"
> 
> get app crash
> ![image](https://user-images.githubusercontent.com/2936985/236781256-0cff2b0b-40d1-4606-a20a-ad14d2f90128.png)
> 
> bugged text stored in chats.json and crash happens again on app restart

Can you download saved chats? Can be partially, with problematic text

**Comment by dreamer2** [comment]
[chats.zip](https://github.com/HemulGM/ChatGPT/files/11419757/chats.zip)

**Comment by HemulGM** [comment]
@dreamer2 It turned out to be a bug in the internal engine. I reported to the developers and made a fix for the client. Compiled with a fix for Windows

**Comment by HemulGM** [comment]
@dreamer2 check pls

**Comment by dreamer2** [comment]
version 1.0.10 from 10.05 still crashes

**Comment by HemulGM** [comment]
Can you make a video with the new version?

**Comment by dreamer2** [comment]
![delphiCrash](https://github.com/HemulGM/ChatGPT/assets/2936985/7d7ed32e-77fa-411d-9072-94bfd07b602a)

**Comment by HemulGM** [comment]
Ahh, my apologies. Missed. should work now)

**Comment by dreamer2** [comment]
fixed
