### ISSUE TITLE
Прыгает размер textbox после переноса строки - macOS ARM64

### ISSUE THREAD

**Issue by StasGrishaevTutu** [HemulGM/ChatGPT#25]
Минорный баг - после переноса строки и дальнейшего ввода текста элемент ввода текста начинает "прыгать" в размере при вводе текста, см. видео - https://github.com/HemulGM/ChatGPT/assets/115224622/e14ec687-9053-40f0-8ca4-2853600685d0

macOS, ARM64

**Comment by HemulGM** [comment]
Да есть такая проблема. Буду бороться по мере возможности. Она известная. Некорректно почему-то высчитывается размер содержимого. Т.е. передается мне некорректное значение, а я его сразу применяю.

**Comment by HemulGM** [comment]
Я поправил проблему. На неделе будет билд для MacOS

**Comment by HemulGM** [comment]
Сборка под Мак готова

**Comment by StasGrishaevTutu** [comment]
проверил, всё хорошо, спасибо !
