### ISSUE TITLE
Chinese prompt error

### ISSUE THREAD

**Issue by alanpeng** [HemulGM/ChatGPT#3]
![image](https://user-images.githubusercontent.com/3273357/222922594-9b1d2875-60db-4559-90f2-237c0a26eec8.png)

**Comment by HemulGM** [comment]
Write test text please

**Comment by HemulGM** [comment]
![image](https://user-images.githubusercontent.com/22197242/222922809-e0dbeda9-863d-46e9-8f70-d30fddd187ea.png)

**Comment by alanpeng** [comment]
that's weird. everything is running well under linux desktop. but it seems cannot handle non-english characters under my windows 10.
macOS is a little more different. I can send Chinese but the return message is not correct.

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/222923993-ebd0bf73-c058-4c31-9778-4d91cd91725e.png)

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/222924043-f05fb38c-30ca-4b0b-8d8f-714ce830366d.png)

**Comment by HemulGM** [comment]
You can try to change the way the text is converted here. Module OpenAI.API.pas in OpenAI lib
![image](https://user-images.githubusercontent.com/22197242/222924106-56585aac-815b-419d-b2a9-f06200cc0a59.png)

**Comment by alanpeng** [comment]
I will give it a try. thank you very much.

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/222939325-89a42d96-4b3b-45b6-b369-d9e64fb14871.png)
![image](https://user-images.githubusercontent.com/3273357/222939338-9139d705-ac57-45f1-aad5-9baaa4ab19ec.png)
![image](https://user-images.githubusercontent.com/3273357/222939419-3240129e-a253-4955-8b8f-929ba64af9e7.png)
There was unrecognized special characters at the end of the returned strings. Could you please tell me how to fix it?

**Comment by alanpeng** [comment]
here are two more samples:
![image](https://user-images.githubusercontent.com/3273357/222939755-55e9a1c4-1e98-4a46-aa5f-9ba17d006f4f.png)
![image](https://user-images.githubusercontent.com/3273357/222939794-d852029d-1fd9-4d78-8e6e-b477e52c75f6.png)

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/222942741-6fc4aabc-e95a-40e5-b2c4-55ed9f93c816.png)

**Comment by HemulGM** [comment]
Send me a few queries or queries that result in an error so I can debug

**Comment by alanpeng** [comment]
If I ask chatGPT just return some chinese characters without any other string like numbers and punctuations, it will works well.

**Comment by HemulGM** [comment]
It's just hard for me to write something in Chinese. I tried through a translator and as you can see above I did not get an error.

**Comment by alanpeng** [comment]
Is it possible that the VPN is affecting the data transfer?

**Comment by HemulGM** [comment]
Shouldn't be a problem

**Comment by HemulGM** [comment]
Shouldn't be a problem

**Comment by alanpeng** [comment]
Here is the binary file I built with Delphi 11
[ChatGPT.zip](https://github.com/HemulGM/ChatGPT/files/10892281/ChatGPT.zip)

a few queries:
请给我讲个笑话吧。
请问地球在这个宇宙存在多长时间了？
请问哪个ji计算机语言的开发效率最高？
请为我制定一份学习计划。

**Comment by HemulGM** [comment]
I'll test it tomorrow, thanks

**Comment by HemulGM** [comment]
I'll test it tomorrow, thanks

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/222977505-7cb8df90-0bdd-4e0f-b14e-944d22452161.png)

Fixed the promblem in this way:
In file OpenAI.API.pas,
(1) replace this line:
Response := TStringStream.Create;
with:
Response := TStringStream.Create('',TEncoding.UTF8);

(2) remove UTF8ToString(RawByteString(ResponseText) as below:
function TOpenAIAPI.ParseResponse<T>(const Code: Int64; const ResponseText: string): T;
begin
  case Code of
    200..299:
      try
        Result := TJson.JsonToObject<T>(ResponseText);
      except
        Result := nil;
      end;
  else
    ParseError(Code, ResponseText);
  end;
  if not Assigned(Result) then
    raise OpenAIExceptionInvalidResponse.Create('Empty or invalid response', '', '', Code);
end;
