### ISSUE TITLE
Кликабельные ссылки в ответе

### ISSUE THREAD

**Issue by StasGrishaevTutu** [HemulGM/ChatGPT#32]
Можно сделать ссылки кликабельными ? Скрин с macOS ARM64
![image](https://github.com/HemulGM/ChatGPT/assets/115224622/f3157c1b-78fa-427b-8900-9af2bd803299)

**Comment by HemulGM** [comment]
Сделал, спасибо за идею. Сборка под Мак будет позже

**Comment by HemulGM** [comment]
Сборка под Мак готова

**Comment by StasGrishaevTutu** [comment]
проверил, всё хорошо, спасибо !
