### ISSUE TITLE
Android 64bit compile error

### ISSUE THREAD

**Issue by kaarigar** [HemulGM/ChatGPT#33]
I get this error when compiling for Android 64bit platform:
`[PAClient Error] Error: E7688 Unable to execute '"C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\java.exe" -cp "c:\program files (x86)\embarcadero\studio\22.0\bin\Android\r8-3.3.28.jar" com.android.tools.r8.D8 --release --min-api 23 --output "C:\Work\AI\ChatGPT\Android64\Debug\ChatGPT.classes" @"C:\Work\AI\ChatGPT\Android64\Debug\dex_list.txt"' (Error 1)
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\collection-1.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\collection-1.0.0.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\core-common-2.0.1.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\core-common-2.0.1.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\core-runtime-2.0.1.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\core-runtime-2.0.1.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\fragment-1.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\fragment-1.0.0.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-common-2.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-common-2.0.0.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-livedata-core-2.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-livedata-core-2.0.0.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-runtime-2.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-runtime-2.0.0.dex.jar
[PAClient Error] Error: E7688 Error in c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar:
[PAClient Error] Error: E7688 java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 Compilation failed with an internal error.
[PAClient Error] Error: E7688 Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:98)
[PAClient Error] Error: E7688 	at com.android.tools.r8.D8.main(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
[PAClient Error] Error: E7688 Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 	at Version.fakeStackEntry(Version_3.3.28.java:0)
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:75)
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
[PAClient Error] Error: E7688 	at com.android.tools.r8.BaseCommand$Builder.build(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
[PAClient Error] Error: E7688 	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
[PAClient Error] Error: E7688 	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:85)
[PAClient Error] Error: E7688 	... 1 more
[PAClient Error] Error: E7688 Caused by: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 	at com.android.tools.r8.utils.j$a.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:21)
[PAClient Error] Error: E7688 	at com.android.tools.r8.BaseCommand$Builder.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
[PAClient Error] Error: E7688 	at com.android.tools.r8.BaseCommand$Builder.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:12)
[PAClient Error] Error: E7688 	at com.android.tools.r8.BaseCommand$Builder.addProgramFiles(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
[PAClient Error] Error: E7688 	at com.android.tools.r8.BaseCommand$Builder.addProgramFiles(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 	at com.android.tools.r8.n.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1058)
[PAClient Error] Error: E7688 	at com.android.tools.r8.n.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 	at com.android.tools.r8.D8Command.parse(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 	... 3 more
[PAClient Error] Error: E7688 	Suppressed: java.lang.RuntimeException: com.android.tools.r8.internal.f: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 		at com.android.tools.r8.internal.DT.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:25)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
[PAClient Error] Error: E7688 		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:24)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.build(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
[PAClient Error] Error: E7688 		... 3 more
[PAClient Error] Error: E7688 	Caused by: com.android.tools.r8.internal.f: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar
[PAClient Error] Error: E7688 		at com.android.tools.r8.internal.DT.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
[PAClient Error] Error: E7688 		at com.android.tools.r8.internal.DT.error(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 		at com.android.tools.r8.utils.j$a.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:22)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.e(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:12)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.addProgramFiles(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:3)
[PAClient Error] Error: E7688 		at com.android.tools.r8.BaseCommand$Builder.addProgramFiles(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 		at com.android.tools.r8.n.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1058)
[PAClient Error] Error: E7688 		at com.android.tools.r8.n.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 		at com.android.tools.r8.D8Command.parse(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
[PAClient Error] Error: E7688 		... 3 more
[PAClient Error] Error: E7688 	Caused by: [CIRCULAR REFERENCE: java.nio.file.NoSuchFileException: c:\program files (x86)\embarcadero\studio\22.0\lib\android\Debug\lifecycle-viewmodel-2.0.0.dex.jar]`

**Comment by HemulGM** [comment]
Your SDK for android is not installed correctly.

**Comment by kaarigar** [comment]
The Android 32bit builds and runs fine. What/where should I look for the android SDK installation issue? Thanks.

**Comment by HemulGM** [comment]
To be honest, I don't know. But I see that your path to the JVM goes to Eclipse. For starters, I would just reinstall or update the SDK. Because the error is related only to the final assembly, and the compilation succeeds. This means there are no errors in the source code.
Yes, and I literally today collected releases for all platforms.
