### ISSUE TITLE
Not opening in android

### ISSUE THREAD

**Issue by TechMorgan** [HemulGM/ChatGPT#34]
The app closes when opening

From:
Android 11
Vivo v15 pro

**Comment by HemulGM** [comment]
What bitness did you try?

**Comment by TechMorgan** [comment]
> What bitness did you try?

x64

**Comment by HemulGM** [comment]
Try again 64 download, I updated yesterday. If problem persists, try 32

**Comment by TechMorgan** [comment]
> Try again 64 download, I updated yesterday. If problem persists, try 32

32bit is working
