### ISSUE TITLE
ubuntu 20.04 error

### ISSUE THREAD

**Issue by edvejak** [HemulGM/ChatGPT#36]
$ ./ChatGPT
./ChatGPT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ChatGPT)
./ChatGPT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./ChatGPT)
./ChatGPT: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ChatGPT)

**Comment by HemulGM** [comment]
You need to install the required packages.
