### ISSUE TITLE
Error in exeeding quote 

### ISSUE THREAD

**Issue by Andriyy2** [HemulGM/ChatGPT#37]
You exceeded your current quota, please check your plan and billing details. - i recived this error.

I used the same API in other programs, all worked well. I reinstalled the program but the error left.

**Comment by HemulGM** [comment]
Well, check the token. The error comes from the server, not from the program

**Comment by Andriyy2** [comment]
I also think so first. So I recreate API - and have the same issue. 
Any other suggestions on how to fix it?

**Comment by Andriyy2** [comment]
https://api.openai.com/v1 is this link correct?

**Comment by HemulGM** [comment]
Creating a new token won't help if you run out of quotas on your free account. Need a new account or pay for a subscription.

**Comment by Andriyy2** [comment]
I have a paid account. 
As I said I used the same api in my mac and win apps. 
The problem is only with Android. 
So I try to solve it.

**Comment by Andriyy2** [comment]
I think the problem is that i used ChatGPT Plus Subscription and not paying for one request.
