### ISSUE TITLE
Error sending data: (12175) Произошла ошибка безопасности

### ISSUE THREAD

**Issue by pochchta** [HemulGM/ChatGPT#38]

**Comment by HemulGM** [comment]
Windows 7?

**Comment by pochchta** [comment]
ChatGPT_Win32.zip, ОС Win7x64

**Comment by HemulGM** [comment]
На Win7 есть проблемы с TLS
https://support.microsoft.com/ru-ru/topic/обновление-для-того-чтобы-включить-протоколы-tls-1-1-и-tls-1-2-в-качестве-безопасных-протоколов-по-умолчанию-в-winhttp-в-windows-c4bd73d2-31d7-761e-0178-11268bb10392
