### ISSUE TITLE
К сожалению не пишет код :С

### ISSUE THREAD

**Issue by Hxcktivist** [HemulGM/ChatGPT#39]
![image](https://github.com/HemulGM/ChatGPT/assets/55938842/d2072ae2-f179-4a57-a7d3-c8402ca3644f)

**Comment by HemulGM** [comment]
Это релизная версия или вы сами собирали?

**Comment by Hxcktivist** [comment]
Релизная версия, очень понравилось то что можно указать свой прокси сервер, что бы не подключаться постоянно к впн)

> Это релизная версия или вы сами собирали?

**Comment by HemulGM** [comment]
Так ведь программе вообще не нужен VPN. И прокси не обязательно. 
По поводу проблемы. Попробуй win32 сборку. И скажи, какая версия винды у тебя

**Comment by Hxcktivist** [comment]
> Так ведь программе вообще не нужен VPN. И прокси не обязательно. По поводу проблемы. Попробуй win32 сборку. И скажи, какая версия винды у тебя

К сожалению Win32 сборка ведет себя так же. 
![image](https://github.com/HemulGM/ChatGPT/assets/55938842/81701b86-82d5-4e36-9419-de37ee1487cb)
Система:
Выпуск	Windows 11 Pro для рабочих станций
Версия	22H2
Дата установки	‎07.‎03.‎2023
Сборка ОС	22621.1848

**Comment by HemulGM** [comment]
В AppData есть папка программы. Там хранятся настройки и чаты в виде json. Скинь json чатов.

**Comment by Hxcktivist** [comment]
оно?

> В AppData есть папка программы. Там хранятся настройки и чаты в виде json. Скинь json чатов.

**Comment by Hxcktivist** [comment]
> В AppData есть папка программы. Там хранятся настройки и чаты в виде json. Скинь json чатов.

[chats.txt](https://github.com/HemulGM/ChatGPT/files/11913106/chats.txt)

**Comment by HemulGM** [comment]
Тебе так модель отвечает (без кода). Ты оригинальный API используешь или какой-то сторонний?
![image](https://github.com/HemulGM/ChatGPT/assets/22197242/5e3b8ec3-d329-436a-91e9-1b4d9e77206e)

**Comment by HemulGM** [comment]
Вот релизная версия Win32 с Github
![image](https://github.com/HemulGM/ChatGPT/assets/22197242/20ac120c-ef74-4a1a-8a25-2ed83c362be6)

**Comment by Hxcktivist** [comment]
[settings.txt](https://github.com/HemulGM/ChatGPT/files/11913314/settings.txt)
Свой Апи полученный на сайте.

**Comment by Hxcktivist** [comment]
Снес настройки, запустил еще раз, теперь работает) Спасибо за ответы!
![image](https://github.com/HemulGM/ChatGPT/assets/55938842/9ba5a3a5-9072-4545-b12f-1ce655fbcf5f)

**Comment by HemulGM** [comment]
Эти настройки - для использования с другими API. А по умолчанию работает официальный OpenAI API.
