### ISSUE TITLE
Math formulas

### ISSUE THREAD

**Issue by alanpeng** [HemulGM/ChatGPT#4]
Is there a plan to provide the rendering function for math formulas?

FYI: https://github.com/karser/QDSEquations

**Comment by HemulGM** [comment]
Well, if you somehow standardize the formula format in the response of the neural network and set it to wrap the formulas in special quotes, then you can port this component to FMX

**Comment by alanpeng** [comment]
Porbabaly we can use LaTex:
![image](https://user-images.githubusercontent.com/3273357/224620601-0f753bf1-410f-4e5a-b481-ed8417a084ad.png)

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/224623757-d70755dd-0003-464d-b741-b5dd55ea82e5.png)
Tampermonkey plugin for chrome:
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

**Comment by HemulGM** [comment]
can you throw off the document or links to resources where you can find a similar standard for recording and displaying such formulas?

**Comment by alanpeng** [comment]
> can you share the document or links to resources where you can find a similar standard for recording and displaying such formulas?

https://en.wikipedia.org/wiki/LaTeX
https://github.com/germandzmitry/TMComplex

**Comment by alanpeng** [comment]
For now, I installed the Tampermonkey plugin and the 456049-openai-chatgpt-latex-auto-render-with-mathjax-v2 plugin script for my Chrome browser. That's javascripts things. I have no very clear idea of how to implement it in your project yet.

**Comment by alanpeng** [comment]
GPT4 has the ability to read images with math formulas. Maybe we can give it a test later.

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/227820585-1e6b4b27-db45-4fdc-8b32-39a2ad1aba63.png)

I would like to close this issue now.
