### ISSUE TITLE
Не отображается код в windows 10

### ISSUE THREAD

**Issue by RimenKo** [HemulGM/ChatGPT#47]
Сделал всё по мотивам https://habr.com/ru/articles/732384/
win 10. включая установку Delphi и импорт пакетов "skia4delphi " и "SVGIconImageList"

Аудио расшифровывает, картинки рисует, а вот код нет.
Подскажите как это можно исправить 
https://rimen.pro/img/2023-09-13_142830.png
https://rimen.pro/img/2023-09-13_142830.png

Подскажите куда копать чтобы это исправить

**Comment by HemulGM** [comment]
Под отладкой запустить и посмотреть на ошибку

**Comment by RimenKo** [comment]
![2023-09-13_142817](https://github.com/HemulGM/ChatGPT/assets/144915314/08ab2f88-caf1-4ce1-b465-6a1f0c88e23e)

**Comment by HemulGM** [comment]
![image](https://github.com/HemulGM/ChatGPT/assets/22197242/4f29f3d4-9934-4951-99d5-6c5b7df0e0e3)

**Comment by HemulGM** [comment]
Запусти под отладкой и запроси код

**Comment by RimenKo** [comment]
> Запусти под отладкой и запроси код у GPT

Спасибо, видимо я совсем нуб... а какой код нужно запустить?
здесь https://github.com/HemulGM/ChatGPT/releases скачал релизную версию и развернул её по мануалу
попробовал открыть ChatGPT.exe в интерфейсе Delphi, но видимо то не то

![2023-09-13_192145](https://github.com/HemulGM/ChatGPT/assets/144915314/986f6c32-d288-4426-942f-84d2e8fd9f06)

**Comment by HemulGM** [comment]
Так подожди. Ты что хочешь делать с программой? Ты её хотел из исходников собрать и собрал, или просто хочешь запустить релизную и пользоваться?

**Comment by HemulGM** [comment]
Потому что для просто запуска программы Делфи и зависимости ставить не надо

**Comment by HemulGM** [comment]
В ТГ напиши. @hemulgm

**Comment by RimenKo** [comment]
> Так подожди. Ты что хочешь делать с программой? Ты её хотел из исходников собрать и собрал, или просто хочешь запустить релизную и пользоваться?

хочу запустить релизную и пользоваться. но вот с этим и беда. Простой код отображает

![2023-09-13_192814](https://github.com/HemulGM/ChatGPT/assets/144915314/3417f24e-e3c6-4a64-9302-28a09a4e60e8)

остальной нет

![2023-09-13_192852](https://github.com/HemulGM/ChatGPT/assets/144915314/03d6131c-aa15-4c7c-9279-83a3034f759e)

возможно я просто много хочу и в этом приложении не срабатывает парсинг ответа... проходит парсинг ответа, чтобы оформить сообщение визуально)  
Если для примера, запросить какой-то другой код, он пришлет корректно, т.к. там не будет каких-то лишних символов, от чего все сбивается и он не приходит
может быть?

**Comment by HemulGM** [comment]
Проблема была с установленным значением автоперевода на англ. и обратно. Google переводчик не переводил и удалял код
