### ISSUE TITLE
Проблемы с отображением элементов

### ISSUE THREAD

**Issue by Atager228** [HemulGM/ChatGPT#5]
Некоторые элементы не отображаются, так же какой-то странный шрифт, после создания билда при запуске ошибка (скриншот 3), если я что-то сделал не так - прошу прощения за потраченное время
![image](https://user-images.githubusercontent.com/51260023/226236548-e2f82c80-5cd9-4305-a5e6-984844e532bb.png)
![image](https://user-images.githubusercontent.com/51260023/226236577-a7b50cac-cd56-4fde-8175-a941d87093c4.png)
![image](https://user-images.githubusercontent.com/51260023/226237277-c3d9defb-40a8-4138-8c5e-fdd22aaa05ae.png)

**Comment by alanpeng** [comment]
Same issue with me.
(1) The 64 bits edition under windows terminated immediately when I start it. The main GUI form did not pop up.
(2) The 32 bits edition under windows promps the same "Runtime error" message.

**Comment by HemulGM** [comment]
Skia.dll needed

**Comment by HemulGM** [comment]
![image](https://user-images.githubusercontent.com/22197242/226526571-9e7064cf-9adb-48da-91d7-c7a236680d6e.png)

**Comment by HemulGM** [comment]
C:\Users\<USERNAME>\Documents\Skia4Delphi\Binary\Shared

**Comment by HemulGM** [comment]
@Atager228, если установить все пакеты корректно (SVGImageList, Skia4Delphi), желательно свежих версий, то всё должно работать как надо.
Runtime error - происходит потому, что ты не положил библиотеку sk4d.dll рядом с исполнительным файлов. Библиотеки под разные платформы находятся здесь (_C:\Users\USERNAME\Documents\Skia4Delphi\Binary\Shared_)

**Comment by alanpeng** [comment]
![image](https://user-images.githubusercontent.com/3273357/227402775-e68f0438-7d6d-4a6b-91ba-8ae8b0f6ac23.png)
This is the right way to fix our problem. I have tested under Windows and Linux desktop.

**Comment by HemulGM** [comment]
This item does more than just that. It also sets a flag in the main program file. Check. This flag replaces the canvas with skia

**Comment by alanpeng** [comment]
> This item does more than just that. It also sets a flag in the main program file. Check. This flag replaces the canvas with skia

Thanks for the comments.
