### ISSUE TITLE
can't run under macOS arm64 Sonoma 14.0

### ISSUE THREAD

**Issue by lidaobing** [HemulGM/ChatGPT#52]
$ open /Applications/ChatGPT_arm64.app/
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000006b0210 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by HemulGM** [comment]
Try changing the permissions on the executable file.
chmod 777 Contents/MacOS/ChatGPT

**Comment by lidaobing** [comment]
`chmod a+x /Applications/ChatGPT_arm64.app/Contents/MacOS/ChatGPT` 后可以使用
