### ISSUE TITLE
 The app doesn't work

### ISSUE THREAD

**Issue by Flooorick** [HemulGM/ChatGPT#54]
When requesting, the error 'content' is a required property - 'messages.0' is output

**Comment by HemulGM** [comment]
Which version?

**Comment by Flooorick** [comment]
The latest version at the moment is 1.0.18.

**Comment by HemulGM** [comment]
> The latest version at the moment is 1.0.18.

Can you post an example request? Or better yet, a file with a history of requests in a folder AppData. The token can be deleted

**Comment by Flooorick** [comment]
Excuse me, could you provide the approximate file path or folder name.

**Comment by Flooorick** [comment]
![Desktop Screenshot 2023 10 20 - 10 22 01 35](https://github.com/HemulGM/ChatGPT/assets/148263678/200e1b2f-9f99-423c-ad72-07a0768ff958)
![Desktop Screenshot 2023 10 20 - 10 22 05 29](https://github.com/HemulGM/ChatGPT/assets/148263678/0aa19be4-5a08-429d-a87a-c59cfa939451)

**Comment by Flooorick** [comment]
![276829359-0aa19be4-5a08-429d-a87a-c59cfa939451](https://github.com/HemulGM/ChatGPT/assets/148263678/67cbf3e0-d201-40cd-a7d2-ce3dd8616001)
![Desktop Screenshot 2023 10 20 - 10 22 01 35](https://github.com/HemulGM/ChatGPT/assets/148263678/08828943-4ecb-45de-9015-754c6c42cf38)

**Comment by HemulGM** [comment]
Try turning off functions. For them to work you need to write them. Functions are loaded from dll.

**Comment by Flooorick** [comment]
![Desktop Screenshot 2023 10 20 - 10 31 22 47](https://github.com/HemulGM/ChatGPT/assets/148263678/3b65218e-4720-4e10-9a3d-539ef919b48c)

**Comment by Flooorick** [comment]
Everything is working, thank you.

**Comment by HemulGM** [comment]
Thank you, I'll look into why the error occurs when functions are enabled but not present.
