### ISSUE TITLE
Error sending data: (12175) 

### ISSUE THREAD

**Issue by NickCher1** [HemulGM/ChatGPT#55]
Произошла ошибка безопасности If the error is due to a timeout, you can increase the response timeout in the general program settings.

**Comment by NickCher1** [comment]
A security error occurred If the error is timeout related, you can increase the response timeout in the general program settings.
Increasing the response timeout does not help. What is wrong?

**Comment by HemulGM** [comment]
What OS?

**Comment by NickCher1** [comment]
Hi
Win 7
Thank for helping! 
--
Отправлено из Mail.ru для Android среда, 01 ноября 2023г., 08:47 +03:00 от HemulGM  ***@***.*** :

**Comment by HemulGM** [comment]
This is a Win7 bug. Google "Windows 7 http tls error"
