### ISSUE TITLE
Cannot run on macOS 13.6.2

### ISSUE THREAD

**Issue by seguri** [HemulGM/ChatGPT#56]
Hi,
I have a `Mac14,10` with macOS 13.6.2 and this is what I get when I try to run the arm version:

```
$ open /Applications/ChatGPT_arm64.app
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002581e60 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by HemulGM** [comment]
Hi. Try this https://github.com/HemulGM/ChatGPT/issues/52

**Comment by seguri** [comment]
Great, thanks! Sorry if I forgot to look into closed issues before opening a new one. Maybe we should pin the solution somewhere or mention it in the release page and/or the main README?
