### ISSUE TITLE
Error sending data (12175) Произошла ошибка безопасности

### ISSUE THREAD

**Issue by serg-avens** [HemulGM/ChatGPT#59]
Добрый день!
Получил ключ, пытаюсь выполнить запрос, получаю ошибку: "Error sending data: (12175) Произошла ошибка безопасности
If the error is due to a timeout, you can increase the response timeout in the general program settings."

**Comment by HemulGM** [comment]
Добрый. Это может быть просто тайм-аут. У них часто сервера забиты, но если всегда такая ошибка, то вероятно нет доступа до сервера. Если что, то с недавних пор требуется VPN и для таких клиентов, как мой.
