### ISSUE TITLE
Memory leak with Chat/Completions streaming mode

### ISSUE THREAD

**Issue by wxinix-caliper** [HemulGM/ChatGPT#6]
OpenAI.Completions.pas, Line 205,  the "Completions" object is created but never gets freed.  It should be freeed after Line 210.

The same problem with OpenAI.Chat.pas, Line 210,  the "Chat" object is created but never gets destroyed.

**Comment by HemulGM** [comment]
Fixed

**Comment by wxinix-caliper** [comment]
Thank you. I have no idea why I reported issue at this repo. Should have reported the issue at the other repo.
