### ISSUE TITLE
A lot of problems with Delphi 12

### ISSUE THREAD

**Issue by Fab8573** [HemulGM/ChatGPT#63]
Hello,

A lot of problems with Delphi 12  : 
1) Unit  Skia.FMX -> FMX.Skia
2) NEW_MEMO => Error if defined. If not defined (in project option / compiler)  error with function ISjon 
3)  Params.Size(TImageSize.x512); 
[dcc32 Error] ChatGPT.FrameChat.pas(879): E2003 Undeclared identifier: 'x512
=> Solution ?
 Params.Size(TImageSize.s512x512);
4) The project ChatGPT.exe raised an exception of class EPresentationProxy with the message 'A Presentation proxy class [TStyledPresentationProxy<ChatGPT.Settings.TStyledComboEdit>] with the presentation name [ComboEdit-style] has already been registered.'
initialization
  TPresentationProxyFactory.Current.Unregister(TComboEdit, TControlType.Styled, TStyledPresentationProxy<FMX.ComboEdit.Style.TStyledComboEdit>);
  TPresentationProxyFactory.Current.Register(TComboEdit, TControlType.Styled, TStyledPresentationProxy<TStyledComboEdit>);.

**Comment by HemulGM** [comment]
Already, just not commit
