### ISSUE TITLE
ChatGPT.Functions.pas won't compile on IOS

### ISSUE THREAD

**Issue by Fab8573** [HemulGM/ChatGPT#64]
Because of : 

>
>  const
>   LibExtMask = {$IFDEF MSWINDOWS} '*.dll'; {$ENDIF}
>                 {$IFDEF LINUX}  '*.so';  {$ENDIF}
>                 {$IFDEF MACOS}  '*.o';  {$ENDIF}
>                 {$IFDEF IOS}  '*.o';  {$ENDIF}
>                 {$IFDEF IOS64}  '*.o';  {$ENDIF}
>                 {$IFDEF ANDROID}  '*.so';  {$ENDIF}

[DCC Erreur] ChatGPT.Functions.pas(16): E2029 Expected statement but constant string found.

Certainly because {$IFDEF MACOS} is active on both IOS and IOS64 :  
https://docwiki.embarcadero.com/RADStudio/Athens/en/Conditional_compilation_(Delphi)

Same for IOS and IOS64 !

Maybe this could be better :

>   LibExtMask = {$IFDEF MSWINDOWS} '*.dll';
>                 {$ELSE IF DEFINED(LINUX)}  '*.so';
>                 {$ELSE IF DEFINED(IOS64) }  '*.o';
>                 {$ELSE IF DEFINED(IOS)}    '*.o';
>                 {$ELSE IF DEFINED(MACOS)}   '*.o';
>                 {$ELSE IF DEFINED(ANDROID)}  '*.so';
>                  {$ENDIF}

**Comment by HemulGM** [comment]
Fixed
