### ISSUE TITLE
On IOS  ChatGPT.dpr(69): F1026 File not found : 'WindowDarkMode\DarkModeApi.Consts.pas'

### ISSUE THREAD

**Issue by Fab8573** [HemulGM/ChatGPT#65]
On IOS (and MacOS and Android ?) :

[DCC Fatal error] ChatGPT.dpr(69): F1026 File not found : 'WindowDarkMode\DarkModeApi.Consts.pas'

Maybe in .DPR (because Dark mode for Window frame (Win only)) : 

>   {$IFDEF MSWINDOWS}
>   DarkModeApi.Consts in 'WindowDarkMode\DarkModeApi.Consts.pas',
>   DarkModeApi.FMX in 'WindowDarkMode\DarkModeApi.FMX.pas',
>   DarkModeApi in 'WindowDarkMode\DarkModeApi.pas',
>   DarkModeApi.Types in 'WindowDarkMode\DarkModeApi.Types.pas',
>   {$ENDIF}

But even if this file exists on library path it will failed : 
> Dark mode for Window frame (Win only)

**Comment by HemulGM** [comment]
Inside, these modules are shielded. The error is connected with something else
