### ISSUE TITLE
TPath.GetHomePath and IOS

### ISSUE THREAD

**Issue by Fab8573** [HemulGM/ChatGPT#66]
TPath.GetHomePath seems to be readonly on IOS ?

So this raise a write error when saving configuration file : 

> constructor TManager.Create(AOwner: TComponent);
> begin
>   inherited;
>   FCanShare := GetCanShare;
>   FAppFolder := TPath.Combine(  TPath.GetHomePath  , 'ChatGPT');
> 

This could work better : 

> constructor TManager.Create(AOwner: TComponent);
> begin
>   inherited;
>   FCanShare := GetCanShare;
>   FAppFolder := TPath.Combine(
>  {$IFDEF IOS}
>   TPath.GetDocumentsPath
>  {$ELSE}
>   TPath.GetHomePath
>  {$ENDIF}
>   , 'ChatGPT');

**Comment by HemulGM** [comment]
Thanks, fixed
