### ISSUE TITLE
Пора бы добавить gpt-4o и gpt-4-turbo

### ISSUE THREAD

**Issue by ERmak148** [HemulGM/ChatGPT#67]
Пора бы добавить gpt-4o и gpt-4-turbo. Кстати, даже когда выбираю модель gpt-4, она все равно отвечает что она gpt-3

**Comment by Gahwa-Gahwa** [comment]
+1 yes, please add support for GPT-4o

**Comment by HemulGM** [comment]
You can enter any model. The list is only for a faster choice.

**Comment by HemulGM** [comment]
> Пора бы добавить gpt-4o и gpt-4-turbo. Кстати, даже когда выбираю модель gpt-4, она все равно отвечает что она gpt-3

По поводу второго замечания. Нужно помнить, что созданный чат ранее запоминает модель, которая стаяла ранее в общих настройках. С момент создания нового чата, у чата свои настройки (кнопка слева от поля ввода промпта). Проверь, что там выбрана нужная тебе модель
