### ISSUE TITLE
Не запускается на Sonoma на M1 Pro

### ISSUE THREAD

**Issue by silverjohnes** [HemulGM/ChatGPT#68]
MacBook M1 Pro
Sonoma 14.4.1 (23E224)
Версия сборок 1.0.18

Обе версии, что для arm64, что для i64, не запускаются с ошибкой "Не удалось открыть программу". Карантин выключен, права дадены, но нет.
![image](https://github.com/HemulGM/ChatGPT/assets/16856482/e4ca9166-9738-4ab5-b857-23aca3ef16fd)

Версия 1.0.16 запускается без проблем.

**Comment by HemulGM** [comment]
Попробуй это
https://github.com/HemulGM/ChatGPT/issues/52
