### ISSUE TITLE
GPT 4o support?

### ISSUE THREAD

**Issue by beyondthetech** [HemulGM/ChatGPT#69]
How can GPT 4o support be added to this app? If possible, can a new binary be built for Android x64?

**Comment by timamus** [comment]
> How can GPT 4o support be added to this app? If possible, can a new binary be built for Android x64?

You can use this [QChatGPT](https://github.com/timamus/QChatGPT) Here, ChatGPT models can always be updated to the latest version. And more stable.

**Comment by HemulGM** [comment]
The model can be specified in text, it is not necessary to use only those that are in the list. However, Gpt4o will not accept images, but will only be used as a test model. Maybe I'll implement multimodality somehow.
