### ISSUE TITLE
Raise AV in TFrameChat.MemoQueryChange when enter text and close program

### ISSUE THREAD

**Issue by ziv2015** [HemulGM/ChatGPT#8]
Raise ACCESS_VIOLATION in TFrameChat.MemoQueryChange in ChatGPT.FrameChat.pas, when enter text in MemoQuery and close program. 

I suggest to fix function:
procedure TFrameChat.MemoQueryChange(Sender: TObject);
begin
  TThread.ForceQueue(nil,
    procedure
    begin
      if not Assigned(LayoutSend) then
        Exit;
      var H: Single :=
        LayoutSend.Padding.Top + LayoutSend.Padding.Bottom +
        MemoQuery.ContentBounds.Height +
        LayoutQuery.Padding.Top + LayoutQuery.Padding.Bottom;
      LayoutSend.Height := Max(LayoutSend.TagFloat, Min(H, 400));
    end);
end;

**Comment by HemulGM** [comment]
Fixed
